name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
permissions:
  contents: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - id: create
        name: Create release
        uses: softprops/action-gh-release@v2
        with:
          name: Mixxx Merge ${{ github.ref_name }}
    outputs:
      upload_url: ${{ steps.create.outputs.upload_url }}
  upload:
    name: Upload asset (${{ matrix.config.asset_name }})
    needs: release
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            asset_file: mixxx-merge
            asset_name: mixxx-merge-linux
          - os: macos-latest
            asset_file: mixxx-merge
            asset_name: mixxx-merge-macos
          - os: windows-latest
            asset_file: mixxx-merge.exe
            asset_name: mixxx-merge-windows.exe
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install --frozen-lockfile && bun run build
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_name: ${{ matrix.config.asset_name }}
          asset_path: ./dist/${{ matrix.config.asset_file }}
          asset_content_type: application/octet-stream
