name: Testing
on: workflow_dispatch
permissions:
  contents: write
jobs:
  build:
    name: Build
    strategy:
      matrix:
        config:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_file: mixxx-merge
            asset_name: mixxx-merge-linux
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_file: mixxx-merge
            asset_name: mixxx-merge-macos
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_file: mixxx-merge.exe
            asset_name: mixxx-merge-windows.exe
    runs-on: ${{ matrix.config.os }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.config.target }}
      - run: cargo build --release --target ${{ matrix.config.target }}
